### ISSUE TITLE
Memory Leak on iOS 10.1.1

### ISSUE THREAD

**Issue by giofid** [Alamofire/AlamofireNetworkActivityIndicator#19] opened 2016-11-10 13:20 UTC
I added `NetworkActivityIndicatorManager.shared.isEnabled = true` in `application:didFinishLaunchingWithOptions:` in my `AppDelegate` and when I profile my app to check for memory leaks, _Instruments_ indicates that there is a leak in `NetworkActivityIndicatorManager` on `NSLock` object.
I attach the stack trace of leak.
![schermata 2016-11-10 alle 14 16 31](https://cloud.githubusercontent.com/assets/13570450/20178184/64807a16-a750-11e6-9d7f-f1e4a38401db.png)

**Comment by cnoon** [comment] 2016-11-20 05:28
Hi @giofid,

Thanks for reporting. I've been able to reproduce the issue in Instruments. Unfortunately there's nothing we can actually do here. It appears to be a bug either in Instruments, the compiler or the runtime. I've submitted rdar://29346787 along with the following sample project. Hopefully we'll get some traction from Apple.

* [DaTesta.zip](https://github.com/Alamofire/AlamofireNetworkActivityIndicator/files/601873/DaTesta.zip)
* [DaTesta Leak.trace.zip](https://github.com/Alamofire/AlamofireNetworkActivityIndicator/files/601874/DaTesta.Leak.trace.zip)

![leak screenshot](https://cloud.githubusercontent.com/assets/169110/20460652/1f911e46-ae9f-11e6-8c08-1af79d0c4c4b.png)

I'm going to close this issue out since there's nothing else we can do here.

Thanks again for reporting. 🍻

**Closed by cnoon** 2016-11-20 05:28 UTC
